### ISSUE TITLE
Mark To-Do

### ISSUE THREAD

**Issue by Spazzinq** [Spazzinq/psrf-printing#5]
- [ ] Mark to review proposal and semester deliverables
- [ ] Will send links to other schools in chat
- [ ] Give access to PaperCut
- [ ] Will put his tasks for me/him on GitHub
- [ ] For next week, delve into technical pieces of printing
